[pytest]
markers =
  asyncio: async tests
  timeout: set per-test timeout
  localstack: integration with localstack
  moto: moto-based AWS mocks

# Coverage configuration
addopts = 
  --strict-markers
  --tb=short
  -ra
  --cov-config=.coveragerc

testpaths = tests

python_files = test_*.py
python_classes = Test*
python_functions = test_*

