# Auto-generated pattern file
# Generated: 2025-10-12 19:55:12

EXTRACTED_PATTERNS = {
    'general': [
        r'\bn\ if\b',  # n if (ratio=1.00, n=7685)
        r'\bn\ we\b',  # n we (ratio=1.00, n=6192)
        r'\bmexicans\b',  # mexicans (ratio=1.00, n=6170)
        r'\bn\ there\b',  # n there (ratio=1.00, n=6081)
        r'\bn\ i\b',  # n i (ratio=1.00, n=5721)
        r'\bn\ it\b',  # n it (ratio=1.00, n=4150)
        r'\bn\ when\b',  # n when (ratio=1.00, n=3983)
        r'\bbi\b',  # bi (ratio=1.00, n=3771)
        r'\bmiddle\ east\b',  # middle east (ratio=1.00, n=3646)
        r'\bthe\ middle\ east\b',  # the middle east (ratio=1.00, n=3646)
        r'\bwith\ mental\b',  # with mental (ratio=1.00, n=3561)
        r'\bthe\ chinese\b',  # the chinese (ratio=1.00, n=3409)
        r'\bcountry\ n\b',  # country n (ratio=1.00, n=3348)
        r'\basians\b',  # asians (ratio=1.00, n=3327)
        r'\bafrican\ americans\b',  # african americans (ratio=1.00, n=3296)
        r'\bmiddle\ eastern\b',  # middle eastern (ratio=1.00, n=3234)
        r'\bthem\ n\b',  # them n (ratio=1.00, n=3160)
        r'\bbitches\b',  # bitches (ratio=1.00, n=3118)
        r'\billness\b',  # illness (ratio=1.00, n=3016)
        r'\bmental\ illness\b',  # mental illness (ratio=1.00, n=3016)
        r'\bn\ she\b',  # n she (ratio=1.00, n=2881)
        r'\bn\ many\b',  # n many (ratio=1.00, n=2850)
        r'\bchinese\ n\b',  # chinese n (ratio=1.00, n=2629)
        r'\beasterners\b',  # easterners (ratio=1.00, n=2425)
        r'\bmiddle\ easterners\b',  # middle easterners (ratio=1.00, n=2425)
        r'\bof\ asian\b',  # of asian (ratio=1.00, n=2399)
        r'\bafrican\ american\b',  # african american (ratio=1.00, n=2348)
        r'\barabs\b',  # arabs (ratio=1.00, n=2313)
        r'\ba\ mental\b',  # a mental (ratio=1.00, n=2174)
        r'\bour\ country\b',  # our country (ratio=1.00, n=2110)
        r'\bn\ my\b',  # n my (ratio=1.00, n=2039)
        r'\bportrayed\b',  # portrayed (ratio=1.00, n=2026)
        r'\bwheelchair\b',  # wheelchair (ratio=1.00, n=2003)
        r'\btrans\ women\b',  # trans women (ratio=1.00, n=1991)
        r'\bmexican\ friends\b',  # mexican friends (ratio=1.00, n=1963)
        r'\byears\ n\b',  # years n (ratio=1.00, n=1894)
        r'\bfrom\ the\ middle\b',  # from the middle (ratio=1.00, n=1884)
        r'\bwomen\ n\b',  # women n (ratio=1.00, n=1856)
        r'\bn\ most\b',  # n most (ratio=1.00, n=1814)
        r'\bhundreds\b',  # hundreds (ratio=1.00, n=1792)
        r'\bhundreds\ of\b',  # hundreds of (ratio=1.00, n=1791)
        r'\bsociety\ n\b',  # society n (ratio=1.00, n=1784)
        r'\bn\ its\b',  # n its (ratio=1.00, n=1774)
        r'\basian\ americans\b',  # asian americans (ratio=1.00, n=1771)
        r'\bdiverse\b',  # diverse (ratio=1.00, n=1735)
        r'\battracted\ to\b',  # attracted to (ratio=1.00, n=1672)
        r'\bcouples\b',  # couples (ratio=1.00, n=1653)
        r'\bnative\ american\b',  # native american (ratio=1.00, n=1641)
        r'\bhave\ n\b',  # have n (ratio=1.00, n=1628)
        r'\bwomen\ and\b',  # women and (ratio=1.00, n=1600)
    ],
    'harassment': [
        r'\bdisabilities\b',  # disabilities (ratio=1.00, n=6304)
        r'\bn\ people\b',  # n people (ratio=1.00, n=4336)
        r'\bn\ if\ you\b',  # n if you (ratio=1.00, n=4140)
        r'\bdisability\b',  # disability (ratio=1.00, n=4117)
        r'\bwith\ disabilities\b',  # with disabilities (ratio=1.00, n=3723)
        r'\bpeople\ with\ disabilities\b',  # people with disabilities (ratio=1.00, n=3723)
        r'\bpeople\ n\b',  # people n (ratio=1.00, n=3493)
        r'\bn\ you\b',  # n you (ratio=1.00, n=3465)
        r'\bn\ it\ is\b',  # n it is (ratio=1.00, n=3345)
        r'\bpeople\ from\b',  # people from (ratio=1.00, n=3209)
        r'\btrans\ people\b',  # trans people (ratio=1.00, n=2961)
        r'\bpeople\ with\ mental\b',  # people with mental (ratio=1.00, n=2810)
        r'\bmentally\ ill\b',  # mentally ill (ratio=1.00, n=2798)
        r'\bn\ there\ are\b',  # n there are (ratio=1.00, n=2529)
        r'\bn\ people\ with\b',  # n people with (ratio=1.00, n=2341)
        r'\bn\ there\ is\b',  # n there is (ratio=1.00, n=2282)
        r'\byou\ cant\b',  # you cant (ratio=1.00, n=2248)
        r'\bdisabilities\ are\b',  # disabilities are (ratio=1.00, n=2141)
        r'\bdiscrimination\b',  # discrimination (ratio=1.00, n=2080)
        r'\bafrican\ americans\ are\b',  # african americans are (ratio=1.00, n=1979)
        r'\bmental\ disabilities\b',  # mental disabilities (ratio=1.00, n=1957)
        r'\bwith\ mental\ disabilities\b',  # with mental disabilities (ratio=1.00, n=1957)
        r'\bafrican\ american\ people\b',  # african american people (ratio=1.00, n=1944)
        r'\bdisabled\ people\b',  # disabled people (ratio=1.00, n=1840)
        r'\bchinese\ people\b',  # chinese people (ratio=1.00, n=1598)
        r'\bmexicans\ are\b',  # mexicans are (ratio=1.00, n=1596)
        r'\bare\ asian\b',  # are asian (ratio=1.00, n=1559)
        r'\bindigenous\ people\b',  # indigenous people (ratio=1.00, n=1548)
        r'\btrans\ women\ are\b',  # trans women are (ratio=1.00, n=1543)
        r'\bare\ often\b',  # are often (ratio=1.00, n=1535)
        r'\bhistory\ n\b',  # history n (ratio=1.00, n=1524)
        r'\bthe\ mentally\b',  # the mentally (ratio=1.00, n=1487)
        r'\bare\ portrayed\b',  # are portrayed (ratio=1.00, n=1426)
        r'\bimmigrants\ are\b',  # immigrants are (ratio=1.00, n=1401)
        r'\brisk\b',  # risk (ratio=1.00, n=1393)
        r'\bwith\ disabilities\ are\b',  # with disabilities are (ratio=1.00, n=1380)
        r'\bare\ hundreds\b',  # are hundreds (ratio=1.00, n=1367)
        r'\bthere\ are\ hundreds\b',  # there are hundreds (ratio=1.00, n=1367)
        r'\bare\ hundreds\ of\b',  # are hundreds of (ratio=1.00, n=1367)
        r'\bare\ criminals\b',  # are criminals (ratio=1.00, n=1345)
        r'\bn\ disabled\b',  # n disabled (ratio=1.00, n=1343)
        r'\bstupid\ and\b',  # stupid and (ratio=1.00, n=1328)
        r'\bn\ indigenous\ people\b',  # n indigenous people (ratio=1.00, n=1303)
        r'\bn\ people\ from\b',  # n people from (ratio=1.00, n=1226)
        r'\ba\ jewish\b',  # a jewish (ratio=1.00, n=1213)
        r'\bpeople\ from\ the\b',  # people from the (ratio=1.00, n=1209)
        r'\bthey\ should\ be\b',  # they should be (ratio=1.00, n=1206)
        r'\bof\ people\ with\b',  # of people with (ratio=1.00, n=1189)
        r'\bdisability\ is\b',  # disability is (ratio=1.00, n=1171)
        r'\bn\ disabled\ people\b',  # n disabled people (ratio=1.00, n=1164)
    ],
    'sexual': [
        r'\bbisexual\b',  # bisexual (ratio=1.00, n=5311)
        r'\bfuck\b',  # fuck (ratio=1.00, n=1599)
        r'\bbisexuality\b',  # bisexuality (ratio=1.00, n=1524)
        r'\bbisexuals\b',  # bisexuals (ratio=1.00, n=1425)
        r'\bheterosexual\b',  # heterosexual (ratio=1.00, n=1391)
        r'\bsex\ couples\b',  # sex couples (ratio=1.00, n=969)
        r'\bfucking\b',  # fucking (ratio=1.00, n=923)
        r'\bsame\ sex\ couples\b',  # same sex couples (ratio=1.00, n=914)
        r'\bbisexual\ there\b',  # bisexual there (ratio=1.00, n=789)
        r'\bbisexual\ there\ are\b',  # bisexual there are (ratio=1.00, n=789)
        r'\byoure\ bisexual\b',  # youre bisexual (ratio=1.00, n=777)
        r'\bsex\ marriage\b',  # sex marriage (ratio=1.00, n=772)
        r'\bsame\ sex\ marriage\b',  # same sex marriage (ratio=1.00, n=772)
        r'\bbe\ bisexual\b',  # be bisexual (ratio=1.00, n=712)
        r'\byour\ sexuality\b',  # your sexuality (ratio=1.00, n=712)
        r'\bbisexuals\ are\b',  # bisexuals are (ratio=1.00, n=709)
        r'\bn\ bisexuals\b',  # n bisexuals (ratio=1.00, n=691)
        r'\bn\ bisexuality\b',  # n bisexuality (ratio=1.00, n=574)
        r'\bim\ bisexual\b',  # im bisexual (ratio=1.00, n=549)
        r'\bn\ bisexuals\ are\b',  # n bisexuals are (ratio=1.00, n=541)
        r'\bbisexuality\ is\b',  # bisexuality is (ratio=1.00, n=469)
        r'\bheterosexual\ couples\b',  # heterosexual couples (ratio=1.00, n=460)
        r'\bsexuality\ is\b',  # sexuality is (ratio=1.00, n=448)
        r'\byour\ sexuality\ is\b',  # your sexuality is (ratio=1.00, n=448)
        r'\bmean\ youre\ bisexual\b',  # mean youre bisexual (ratio=1.00, n=444)
        r'\bopposite\ sex\b',  # opposite sex (ratio=1.00, n=431)
        r'\bnot\ bisexual\b',  # not bisexual (ratio=1.00, n=421)
        r'\bbisexual\ you\b',  # bisexual you (ratio=1.00, n=421)
        r'\bnot\ bisexual\ you\b',  # not bisexual you (ratio=1.00, n=421)
        r'\bthe\ bisexual\b',  # the bisexual (ratio=1.00, n=401)
        r'\bsex\ marriages\b',  # sex marriages (ratio=1.00, n=388)
        r'\bsame\ sex\ marriages\b',  # same sex marriages (ratio=1.00, n=388)
        r'\bthe\ opposite\ sex\b',  # the opposite sex (ratio=1.00, n=376)
        r'\bsex\ n\b',  # sex n (ratio=1.00, n=374)
        r'\bopposite\ sex\ n\b',  # opposite sex n (ratio=1.00, n=374)
        r'\bbisexual\ if\b',  # bisexual if (ratio=1.00, n=364)
        r'\bbisexual\ if\ youre\b',  # bisexual if youre (ratio=1.00, n=364)
        r'\bare\ sexual\b',  # are sexual (ratio=1.00, n=354)
        r'\bsexual\ deviants\b',  # sexual deviants (ratio=1.00, n=354)
        r'\bare\ sexual\ deviants\b',  # are sexual deviants (ratio=1.00, n=354)
        r'\ba\ heterosexual\b',  # a heterosexual (ratio=1.00, n=353)
        r'\bin\ a\ heterosexual\b',  # in a heterosexual (ratio=1.00, n=352)
        r'\bdresses\ sexy\b',  # dresses sexy (ratio=1.00, n=326)
        r'\bsexy\ she\b',  # sexy she (ratio=1.00, n=326)
        r'\bwoman\ dresses\ sexy\b',  # woman dresses sexy (ratio=1.00, n=326)
        r'\bdresses\ sexy\ she\b',  # dresses sexy she (ratio=1.00, n=326)
        r'\bsexy\ she\ is\b',  # sexy she is (ratio=1.00, n=326)
        r'\bheterosexual\ relationships\b',  # heterosexual relationships (ratio=1.00, n=324)
        r'\bheterosexual\ relationships\ n\b',  # heterosexual relationships n (ratio=1.00, n=324)
        r'\bbeing\ bisexual\b',  # being bisexual (ratio=1.00, n=318)
    ],
    'violence': [
        r'\beven\ killed\b',  # even killed (ratio=1.00, n=754)
        r'\bkilled\ off\b',  # killed off (ratio=1.00, n=754)
        r'\bwere\ even\ killed\b',  # were even killed (ratio=1.00, n=754)
        r'\beven\ killed\ off\b',  # even killed off (ratio=1.00, n=754)
        r'\bkilled\ off\ n\b',  # killed off n (ratio=1.00, n=754)
        r'\bbeen\ attacked\b',  # been attacked (ratio=1.00, n=608)
        r'\bhave\ been\ attacked\b',  # have been attacked (ratio=1.00, n=608)
        r'\bbeen\ attacked\ and\b',  # been attacked and (ratio=1.00, n=608)
        r'\battacked\ and\ threatened\b',  # attacked and threatened (ratio=1.00, n=608)
        r'\bface\ attacks\b',  # face attacks (ratio=1.00, n=589)
        r'\battacks\ it\b',  # attacks it (ratio=1.00, n=589)
        r'\boppression\ face\ attacks\b',  # oppression face attacks (ratio=1.00, n=589)
        r'\bface\ attacks\ it\b',  # face attacks it (ratio=1.00, n=589)
        r'\battacks\ it\ is\b',  # attacks it is (ratio=1.00, n=589)
        r'\bhurtful\b',  # hurtful (ratio=1.00, n=586)
        r'\bbeing\ hurtful\b',  # being hurtful (ratio=1.00, n=586)
        r'\bhurtful\ so\b',  # hurtful so (ratio=1.00, n=586)
        r'\bthem\ being\ hurtful\b',  # them being hurtful (ratio=1.00, n=586)
        r'\bbeing\ hurtful\ so\b',  # being hurtful so (ratio=1.00, n=586)
        r'\bhurtful\ so\ i\b',  # hurtful so i (ratio=1.00, n=586)
        r'\bin\ attacks\b',  # in attacks (ratio=1.00, n=575)
        r'\bincrease\ in\ attacks\b',  # increase in attacks (ratio=1.00, n=575)
        r'\bin\ attacks\ against\b',  # in attacks against (ratio=1.00, n=575)
        r'\battacks\ against\ asian\b',  # attacks against asian (ratio=1.00, n=575)
        r'\bkill\ the\b',  # kill the (ratio=1.00, n=553)
        r'\bto\ kill\ the\b',  # to kill the (ratio=1.00, n=549)
        r'\bneed\ to\ kill\b',  # need to kill (ratio=1.00, n=547)
        r'\bkill\ the\ chinese\b',  # kill the chinese (ratio=1.00, n=547)
        r'\bkills\b',  # kills (ratio=1.00, n=424)
        r'\bto\ skills\b',  # to skills (ratio=1.00, n=418)
        r'\bskills\ in\b',  # skills in (ratio=1.00, n=418)
        r'\bthem\ to\ skills\b',  # them to skills (ratio=1.00, n=418)
        r'\bto\ skills\ in\b',  # to skills in (ratio=1.00, n=418)
        r'\bskills\ in\ computer\b',  # skills in computer (ratio=1.00, n=418)
        r'\bwho\ kills\b',  # who kills (ratio=1.00, n=414)
        r'\bkills\ an\b',  # kills an (ratio=1.00, n=414)
        r'\bofficer\ who\ kills\b',  # officer who kills (ratio=1.00, n=414)
        r'\bwho\ kills\ an\b',  # who kills an (ratio=1.00, n=414)
        r'\bkills\ an\ unarmed\b',  # kills an unarmed (ratio=1.00, n=414)
        r'\bhurt\ the\b',  # hurt the (ratio=1.00, n=411)
        r'\band\ hurt\b',  # and hurt (ratio=1.00, n=410)
        r'\bschools\ and\ hurt\b',  # schools and hurt (ratio=1.00, n=410)
        r'\band\ hurt\ the\b',  # and hurt the (ratio=1.00, n=410)
        r'\bhurt\ the\ quality\b',  # hurt the quality (ratio=1.00, n=410)
        r'\bterrorist\ attacks\b',  # terrorist attacks (ratio=1.00, n=386)
        r'\battacks\ increase\b',  # attacks increase (ratio=1.00, n=386)
        r'\bterrorist\ attacks\ increase\b',  # terrorist attacks increase (ratio=1.00, n=386)
        r'\battacks\ increase\ the\b',  # attacks increase the (ratio=1.00, n=386)
        r'\bfrom\ hurting\b',  # from hurting (ratio=1.00, n=376)
        r'\bhurting\ others\b',  # hurting others (ratio=1.00, n=376)
    ],
    'threat': [
        r'\balways\ going\ to\b',  # always going to (ratio=1.00, n=264)
        r'\bwere\ going\ to\b',  # were going to (ratio=1.00, n=79)
        r'\bgoing\ to\ be\b',  # going to be (ratio=0.98, n=358)
        r'\bgoing\ to\b',  # going to (ratio=0.93, n=454)
        r'\bwatch\ out\b',  # watch out (ratio=0.90, n=9)
        r'\bgoing\ to\ the\b',  # going to the (ratio=0.89, n=8)
        r'\bis\ going\ to\b',  # is going to (ratio=0.89, n=8)
        r'\bgoing\ to\ get\b',  # going to get (ratio=0.88, n=7)
        r'\bnot\ going\ to\b',  # not going to (ratio=0.86, n=6)
        r'\bam\ going\ to\b',  # am going to (ratio=0.83, n=5)
        r'\bwas\ going\ to\b',  # was going to (ratio=0.83, n=5)
        r'\bm\ going\ to\b',  # m going to (ratio=0.79, n=26)
        r'\bare\ going\ to\b',  # are going to (ratio=0.71, n=5)
    ],
    'self_harm': [
        r'\bto\ suicide\b',  # to suicide (ratio=1.00, n=45)
        r'\bsuicide\ n\b',  # suicide n (ratio=1.00, n=45)
        r'\bleads\ to\ suicide\b',  # leads to suicide (ratio=1.00, n=45)
        r'\bto\ suicide\ n\b',  # to suicide n (ratio=1.00, n=45)
        r'\bsuicide\b',  # suicide (ratio=0.94, n=49)
    ],
}
