{{- if or .Values.secrets.openaiApiKey .Values.secrets.azureEndpoint .Values.secrets.azureKey .Values.secrets.slackWebhookUrl .Values.secrets.sessionSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "safety-eval-mini.fullname" . }}
  labels:
    {{- include "safety-eval-mini.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.openaiApiKey }}
  openai-api-key: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.azureEndpoint }}
  azure-endpoint: {{ .Values.secrets.azureEndpoint | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.azureKey }}
  azure-key: {{ .Values.secrets.azureKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.slackWebhookUrl }}
  slack-webhook-url: {{ .Values.secrets.slackWebhookUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.sessionSecret }}
  session-secret: {{ .Values.secrets.sessionSecret | b64enc | quote }}
  {{- end }}
{{- end }}

